# Generated by Django 2.2.9 on 2020-02-05 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_text', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_text', models.CharField(max_length=200)),
                ('apellidos_text', models.CharField(default='', max_length=200)),
                ('fechaNac_datetime', models.DateTimeField(verbose_name='fecha nacimiento')),
            ],
        ),
        migrations.CreateModel(
            name='Sexo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_text', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_text', models.CharField(max_length=100)),
                ('apellidos_text', models.CharField(max_length=100)),
                ('fechaNac_datetime', models.DateTimeField(verbose_name='fecha nacimiento')),
                ('mail_text', models.EmailField(max_length=200)),
                ('usuario_text', models.CharField(max_length=200)),
                ('password_text', models.CharField(max_length=200)),
                ('SIP_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Toma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_text', models.CharField(max_length=200)),
                ('activa', models.IntegerField(default=0)),
                ('persona_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifyMed.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='sexo_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notifyMed.Sexo'),
        ),
        migrations.AddField(
            model_name='persona',
            name='usuario_text',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='notifyMed.Usuario'),
        ),
    ]
