# Generated by Django 2.2.7 on 2020-02-06 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifyMed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_text', models.CharField(max_length=200)),
                ('cantidad_text', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PrincipioActivo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TipoToma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_text', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='toma',
            name='dias_text',
            field=models.ManyToManyField(to='notifyMed.Dia'),
        ),
        migrations.AddField(
            model_name='toma',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_text', models.CharField(max_length=10)),
                ('cantidadPorToma_text', models.CharField(max_length=10)),
                ('FechaInicio_datetime', models.DateTimeField(verbose_name='Fecha de inicio')),
                ('Fechafin_datetime', models.DateTimeField(verbose_name='Fecha de Finalización')),
                ('medicamento_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifyMed.Medicamento')),
                ('persona_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifyMed.Persona')),
            ],
        ),
        migrations.AddField(
            model_name='medicamento',
            name='PrincipiosActivos_text',
            field=models.ManyToManyField(to='notifyMed.PrincipioActivo'),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='TipoToma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifyMed.TipoToma'),
        ),
        migrations.AddField(
            model_name='toma',
            name='horas_text',
            field=models.ManyToManyField(to='notifyMed.Hora'),
        ),
        migrations.AddField(
            model_name='toma',
            name='medicamento_text',
            field=models.ManyToManyField(to='notifyMed.Medicamento'),
        ),
    ]
