# Generated by Django 2.2.7 on 2020-02-11 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifyMed', '0002_auto_20200206_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='SIP_text',
            field=models.CharField(default='', max_length=200),
        ),
    ]
